### ISSUE TITLE
Issue for datasets

### ISSUE THREAD

**Issue by Roronoayx** [wangtianyu61/contextual-bandit-experiment#1]
So great to find your code about CB on Github😊

I can't find the MSOM_Hotel and CPRM-12-001 datasets anywhere, are they still available to access online? Or what keyword should I use to possibly find them?

Thanks!

**Comment by wangtianyu61** [comment]
Hi,
Thanks for your interest. The MSOM_Hotel dataset is based on this paper: [link](https://pubsonline.informs.org/doi/epdf/10.1287/msom.1080.0231).
The CPRM-12-001, unfortunately, was originally on the Columbia business school website [link](https://business.columbia.edu/cprm/research/data-sets) upon request by sending them a form. However, it seems that the dataset is not there anymore.

**Comment by Roronoayx** [comment]
> Hi, Thanks for your interest. The MSOM_Hotel dataset is based on this paper: [link](https://pubsonline.informs.org/doi/epdf/10.1287/msom.1080.0231). The CPRM-12-001, unfortunately, was originally on the Columbia business school website [link](https://business.columbia.edu/cprm/research/data-sets) upon request by sending them a form. However, it seems that the dataset is not there anymore.

Thanks a lot for your detailed answer😆. The information you provided is very helpful. I'll try to reach out to the Columbia business school to see if there's a possibility to obtain the dataset. Thanks again for your time and effort.
